In [1]:
import numpy as np


In [11]:
#Ques1:
import numpy as np
np.random.seed(4)
x=np.random.randint(1,100,(10,10))

print("Original Array:")
print(x)

A=x[0:5,0:7]
B=x[0:7,0:5]
C=x[5:10,3:10]

print("A:")
print(A)

print("B:")
print(B)

print("C:")
print(C)

print("Sum of A and C:")
print(A + C)

print("Multiplication of A and B:")
print(A @ B)

Original Array:
[[47 56 70  2 88 73 51 10 59 95]
 [56 56 58 37 51 45 39 53  4  1]
 [56 22 22 74 39 57 67 47 31  9]
 [50 67 59 88 33 41 43 46 34 33]
 [29  4 80 99 96 58 51 18 82 90]
 [74 60 49 77 24 95 23 68 63 63]
 [76 24 57 71 72 74 83 56 54 86]
 [95 80 37 92 60 52  9 38 73 60]
 [55 97 31  5 55 76  9 32 41 18]
 [79 10 54 69 63 60  4  5 40 55]]
A:
[[47 56 70  2 88 73 51]
 [56 56 58 37 51 45 39]
 [56 22 22 74 39 57 67]
 [50 67 59 88 33 41 43]
 [29  4 80 99 96 58 51]]
B:
[[47 56 70  2 88]
 [56 56 58 37 51]
 [56 22 22 74 39]
 [50 67 59 88 33]
 [29  4 80 99 96]
 [74 60 49 77 24]
 [76 24 57 71 72]]
C:
[[77 24 95 23 68 63 63]
 [71 72 74 83 56 54 86]
 [92 60 52  9 38 73 60]
 [ 5 55 76  9 32 41 18]
 [69 63 60  4  5 40 55]]
Sum of A and C:
[[124  80 165  25 156 136 114]
 [127 128 132 120 107  99 125]
 [148  82  74  83  77 130 127]
 [ 55 122 135  97  65  82  61]
 [ 98  67 140 103 101  98 106]]
Multiplication of A and B:
[[21195 13398 21720 25476 23660]
 [18639 13867 19135 21015 20051]
 [19237 14

In [12]:
#Ques2:
np.random.seed(5)
x=np.random.randint(1,100,(10,10))

print("Original Array:")
print(x)

#2D reshapes
print("\n1 * 100:")
print(x.reshape(1,100))
print("\n2 * 50:")
print(x.reshape(2,50))
print("\n4 * 25:")
print(x.reshape(4,25))
print("\n5 * 20:")
print(x.reshape(5,20))
print("\n10 * 10:")
print(x.reshape(10,10))
print("\n20 * 5:")
print(x.reshape(20,5))
print("\n25 * 4:")
print(x.reshape(25,4))
print("\n50 * 2:")
print(x.reshape(50,2))
print("\n100 * 1:")
print(x.reshape(100,1))

#3D reshapes
print("\n2 * 5 * 10:")
print(x.reshape(2,5,10))
print("\n2 * 10 * 5:")
print(x.reshape(2,10,5))
print("\n5 * 2 * 10:")
print(x.reshape(5,2,10))
print("\n5 * 10 * 2:")
print(x.reshape(5,10,2))
print("\n10 * 2 * 5:")
print(x.reshape(10,2,5))
print("\n10 * 5 * 2:")
print(x.reshape(10,5,2))

Original Array:
[[79 62 17 74  9 63 28 31 81  8]
 [77 16 54 81 28 45 78 76 66 48]
 [31 85 87 19 10 42 63  2 83 17]
 [79  6 59  1 81  5 37 52 28 32]
 [ 3 69 39 84 20 19  8 31 63 12]
 [68 66 56  4 92 79 28 30 34 90]
 [86  8 17 95 15 91 32 10 39 48]
 [17  6 35 46 60 25 14 32 33 77]
 [45  6 15 48 95 83  1  8 87 17]
 [65  9 91 45 38 95 76  6 23 53]]

1 * 100:
[[79 62 17 74  9 63 28 31 81  8 77 16 54 81 28 45 78 76 66 48 31 85 87 19
  10 42 63  2 83 17 79  6 59  1 81  5 37 52 28 32  3 69 39 84 20 19  8 31
  63 12 68 66 56  4 92 79 28 30 34 90 86  8 17 95 15 91 32 10 39 48 17  6
  35 46 60 25 14 32 33 77 45  6 15 48 95 83  1  8 87 17 65  9 91 45 38 95
  76  6 23 53]]

2 * 50:
[[79 62 17 74  9 63 28 31 81  8 77 16 54 81 28 45 78 76 66 48 31 85 87 19
  10 42 63  2 83 17 79  6 59  1 81  5 37 52 28 32  3 69 39 84 20 19  8 31
  63 12]
 [68 66 56  4 92 79 28 30 34 90 86  8 17 95 15 91 32 10 39 48 17  6 35 46
  60 25 14 32 33 77 45  6 15 48 95 83  1  8 87 17 65  9 91 45 38 95 76  6
  23 53]]

4 * 25

In [14]:
#Ques3:
np.random.seed(42)
x=np.random.randint(10,99,(6,6))

print("Original Array:")
print(x)

print("Sum of each row:")
print(x.sum(axis=1))

print("Sum of each column:")
print(x.sum(axis=0))

print("Mean of each row:")
print(np.round((x.mean(axis=1)),2))

print("Maximum value in each row:")
print(x.max(axis=1))

print("Column index of max value in each row:")
print(x.argmax(axis=1))

print("Array converted to float datatype:")
y=x.astype('float')
print(y)

Original Array:
[[61 24 81 70 30 92]
 [96 84 84 97 33 12]
 [31 62 11 97 39 47]
 [11 73 69 30 42 85]
 [67 31 98 58 68 51]
 [69 89 24 71 71 56]]
Sum of each row:
[358 406 287 310 373 380]
Sum of each column:
[335 363 367 423 283 343]
Mean of each row:
[59.67 67.67 47.83 51.67 62.17 63.33]
Maximum value in each row:
[92 97 97 85 98 89]
Column index of max value in each row:
[5 3 3 5 2 1]
Array converted to float datatype:
[[61. 24. 81. 70. 30. 92.]
 [96. 84. 84. 97. 33. 12.]
 [31. 62. 11. 97. 39. 47.]
 [11. 73. 69. 30. 42. 85.]
 [67. 31. 98. 58. 68. 51.]
 [69. 89. 24. 71. 71. 56.]]


In [19]:
#Ques4:
x=np.arange(1,21)
print("Arranged Array:")
print(x)

x=x.reshape(4,5)
print("Reshaped Array:")
print(x)

sub=x[1:3,2:5]
print("Extracted subarray:")
print(sub)

variance=np.var(sub)
std=np.std(sub)

print("Variance:",variance)
print("Standard Deviation:",std)

Arranged Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reshaped Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Extracted subarray:
[[ 8  9 10]
 [13 14 15]]
Variance: 6.916666666666667
Standard Deviation: 2.6299556396765835


In [38]:
#Ques5:
np.random.seed(21)
x=np.random.uniform(50,150,8)
print("Raw Array:")
print(x)

print("Values rounded to 2 decimal places:")
rounded=np.round(x,2)
print(rounded)

zeros=np.zeros((2,4))
ones=np.ones((2,4))
print("\nZeros:")
print(zeros)
print("\nOnes:")
print(ones)

reshaped=rounded.reshape(2,4)
print("\nReshaped Array:")
print(reshaped)

result = reshaped+10
print("\nAfter adding 10:")
print(result)

Raw Array:
[ 54.87248808  78.91096598 122.09663468  52.16162499  70.59227653
  55.07732567  80.2271894  116.39102946]
Values rounded to 2 decimal places:
[ 54.87  78.91 122.1   52.16  70.59  55.08  80.23 116.39]

Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Reshaped Array:
[[ 54.87  78.91 122.1   52.16]
 [ 70.59  55.08  80.23 116.39]]

After adding 10:
[[ 64.87  88.91 132.1   62.16]
 [ 80.59  65.08  90.23 126.39]]
